### ISSUE TITLE
No effect on 'justify-content' when the child elements are h3-h5

### ISSUE THREAD

**Issue by lukaskoeller** [philipwalton/flexbugs#59] opened 2015-06-10 21:04 UTC
HTML:
`<div class="block-header">
	<h3>headline h3</h3>
	<h5>headline h5</h5>
<div>`

CSS:
`.block-header {
    width: 100%;
    display: flex;
    justify-content: space-between;
}`

The Browsers always showing something like a `space-around`, also when `justify-content` isn't set.
I tested in the latest Firefox (38.0.05) and Chrome version 43.0.2357.124 m. Good possible that this bug is exist also for h1,h2,h4 and h6.

**Comment by jpdevries** [comment] 2015-06-10 22:20
Here's a [codepen](http://codepen.io/jpdevries/pen/JdJEpy) with your example. `justify-content` seems to have an effect in the browsers you mention. Try commenting out or change `justify-content` on line 4.

I tested in 
 - Firefox (38.0.5)
 - Chrome
 - Safari

**Comment by philipwalton** [comment] 2015-06-11 00:00
Closing as I cannot reproduce this bug. If you'd like me to reopen, please put together a demo so I can see what's wrong.

**Closed by philipwalton** 2015-06-11 00:00 UTC

**Comment by lukaskoeller** [comment] 2015-06-11 08:03
Yes, your're right! I also created a jsfiddle and everything worked fine. Never the less, this problem still exist in my project. I made a screenshot in firefox to below.
![bug](https://cloud.githubusercontent.com/assets/10390627/8102535/1c775676-1021-11e5-8f1a-47e61c9dc4dd.PNG)

**Comment by jpdevries** [comment] 2015-06-11 14:36
Until we've reproduced the issue with a simple example there's no way to know if you are dealing with an actual bug or something specific to your project.

**Comment by lukaskoeller** [comment] 2015-06-11 15:08
Yes, you're right again. I got a closer look into my code and find out, that `margin: 0 auto` was the problem especially the `auto`. However. I'm not an expert but it seems to me like it's not normal, that both child elements are positioned that way?

**Comment by jpdevries** [comment] 2015-06-11 15:14
I don't think you've presented anything that isn't normal. margin: 0 auto is expected to affect how things are laid out especially when used with text-align:center. 
There doesn't seem to be a flexbug here.

**Comment by lukaskoeller** [comment] 2015-06-11 15:30
Ah okay. I created another fiddle to get that. I'm very sorry!
