### ISSUE TITLE
Google Chrome Flex-Grow Bug

### ISSUE THREAD

**Issue by walexy** [philipwalton/flexbugs#31] opened 2015-04-02 21:57 UTC
-webkit-flex: 0.0000001 0 auto; 
0.0000001 to correct flex grow bug
https://code.google.com/p/chromium/issues/detail?id=460510

**Comment by gregwhitworth** [comment] 2015-04-03 15:32
And I'm off to work, but so others don't have to build the test page: http://jsbin.com/jiciyiyefu/2/edit?html,css,output

I have tested this in Chrome 41/IE 11+/Firefox. IE11 is not working at all, and I haven't had a chance to test his workaround for Chrome 41. Firefox and Project Spartan work as expected. I'll take a look at this this weekend and write up the workaround.

**Comment by philipwalton** [comment] 2016-04-21 01:10
Is this a duplicate of #140?

**Comment by gregwhitworth** [comment] 2016-04-25 22:55
@philipwalton It definately appears that way. But honestly, my head hurts, #140 links to #116. I would suggest closing them all out since they all seem to work in the later Chrome/Firefox/Edge unless we expect a decent amount of people to get stuck on a Chrome version where the issue manifests itself. Thoughts?

**Closed** 2016-04-26 18:40 UTC
