### ISSUE TITLE
Bug #1 has a Firefox bug tracking number but Firefox isn't listed in the affected browsers

### ISSUE THREAD

**Issue by IshmaelYavitz** [philipwalton/flexbugs#103] opened 2015-11-27 06:37 UTC
Accidental omission?  Or is there a more complex reason?

**Comment by philipwalton** [comment] 2015-11-27 23:33
If you look at the bug description, you'll see it's not a bug to implement the feature, it's a bug to track any negative consequences *after* implementing the feature.

I do think you bring up a fair point though. I can see how it could be confusing if you didn't read the bug and were just looking at the table. Maybe it's worth removing since it's pretty clear the feature isn't going away.

**Comment by philipwalton** [comment] 2015-11-27 23:34
Closed via 2aa9804225f12becc03fa574809bd97c16a4f051.

**Closed by philipwalton** 2015-11-27 23:34 UTC
