### ISSUE TITLE
justify-content with child-elements using flex-grow broken in Chrome and IE11

### ISSUE THREAD

**Issue by MattyBalaam** [philipwalton/flexbugs#116] opened 2016-01-08 14:25 UTC
If a parent element has justify-content set, and the child/children use flex-grow, then it acts as flex-start only.

Tested working in Firefox and Edge.

Codepen example: http://codepen.io/MattyBalaam/pen/JGNNXx

**Comment by eikaramba** [comment] 2016-01-10 01:16
can you provide a screenshot? Because on my FF 44.0b7 it is working as expected and apart from the growing container the upper and lower boxes are always aligend in the same way

**Comment by MattyBalaam** [comment] 2016-01-10 02:02
As I said, Firefox and Edge work as expected, Chrome and IE are broken.

**Comment by eikaramba** [comment] 2016-01-10 02:05
Ah sry, my bad. I just learn to read :)

Anyway i tested it on chrome 47.0.2526.106 and it is working there too, exactly as in FF.

**Comment by MattyBalaam** [comment] 2016-01-10 08:58
Hmm, OK, I have just tested on a mac laptop and it is fine there, but it was broken on my work Windows 7 where I noticed the issue. I will look again tomorrow when i am back at work.

**Comment by philipwalton** [comment] 2016-01-10 18:22
I also see them looking exactly the same. I'm going to close this issue, but feel free to reopen if you're able to reproduce the bug again.

**Closed by philipwalton** 2016-01-10 18:22 UTC

**Comment by MattyBalaam** [comment] 2016-01-10 19:30
I just started up a browser stack session with Windows 7. I can’t now reproduce on Chrome, which suggests something odd happening the machine I originally noticed my issue.

However, I can see the IE11 issue and have made a screeshot..

![screen shot 2016-01-10 at 19 27 57](https://cloud.githubusercontent.com/assets/1246923/12223475/a354a386-b7d0-11e5-8910-aa137921445a.png)

**Comment by philipwalton** [comment] 2016-01-10 19:43
After looking at this a little more, I think IE is actually rendering this correctly and Chrome/FF/Edge are wrong.

This is how the spec says to calculate grow factor:

> Find the ratio of the item’s flex grow factor to the sum of the flex grow factors of all unfrozen items on the line. Set the item’s target main size to its flex base size plus a fraction of the remaining free space proportional to the ratio.

The grow factor is `0.1` and since there's only one flex item the total grow factor is also `0.1`, which means it should take up 100% of the available space (`0.1 / 0.1 = 100%`).

@gregwhitworth is this correct? Is Edge doing it wrong here?

In general, I don't know why you're using a fractional grow factor. I suspect you think that grow means something different from what it actually means. I'd stick to integer values for grow/shrink because they're easier to reason about (and it avoids this bug).

**Comment by MattyBalaam** [comment] 2016-01-11 08:48
OK, now looking I was looking on Chrome 48.0.2564.71 beta-m (64-bit), so I will file a bug elsewhere.

I think you may be right that I am using Flexbox in a way it is probably not supposed to work. As to why I was trying fractional grow, it is to solve the problem here: http://stackoverflow.com/questions/34651752/matching-widths-of-elements-with-dynamic-content-along-a-row-using-css-only?noredirect=1#comment57088151_34651752

But yes, probably more of a hack.

**Comment by gregwhitworth** [comment] 2016-01-11 22:24
@philipwalton @MattyBalaam This is per spec, but is found in the resolving of the [fr units](https://drafts.csswg.org/css-flexbox-1/#resolve-flexible-lengths) instead of the other algo, particularly this line within the loop (bullet 4):

> If the **sum of the unfrozen flex items’ flex factors is less than one**, multiply the initial free space by this sum. If the magnitude of this value is less than the magnitude of the remaining free space, use this as the remaining free space.

So in this case, it is indeed less than 1, so we actually only give it 10% of the remaining free space. Hope that helps.

**Comment by philipwalton** [comment] 2016-01-12 00:56
Thanks @gregwhitworth, I must have missed that part!

**Comment by MattyBalaam** [comment] 2016-01-12 09:03
Being investigated: https://code.google.com/p/chromium/issues/detail?id=576202

**Comment by MattyBalaam** [comment] 2016-02-03 13:51
This is now happening on stable 32-bit version 48.0.2564.97 m
