### ISSUE TITLE
Column wrap is behaving differently in safari and in chrome.

### ISSUE THREAD

**Issue by vishal9p** [philipwalton/flexbugs#227] opened 2017-06-22 06:15 UTC
I have a codepen designed where i have used column wrap for aligning the items.
CodePen Link:----->(below)
[](https://codepen.io/vish123/full/OgmvWz/)
https://codepen.io/vish123/full/OgmvWz/
**Steps to reproduce the issue**:
Open the above codepen link in chrome and in safari,we can see the difference in the alignment(Attached the screen-shot).
SAFARI:->
In case of safari browser there is a extra space between the flex container and the flex items where the column wrap is applied.The width of the flex container is more than the children.
CHROME:->
In case of chrome browser there is no extra space between the flex container and the flex items where the column wrap is applied. The width of the flex container is exactly equal to the the children.That is there is no space between the flex container and flex item where this column wrap is applied.

**Now i am bit confused which behaviour is actually correct the chrome one or the safari.**Please clarify this.Using flex-direction:column instead of column wrap fixes the issue but i have to use column-wrap i cannot use column as the flex-direction.Also flex-grow:1 is not a valid solution.

So which behaviour is correct the chrome one, where the flex container takes width exactly equal to to their children or the safari one , where the width of the flex container is bit more than the child items.please clarify this and also provide the fix if any exist.

Snapshot of codepen in SAFARI:
<img width="1280" alt="safari snapshot of codepen" src="https://user-images.githubusercontent.com/9588595/27417322-243324f4-5731-11e7-83f6-31c891b8de87.png">

Snapshot of codepen in CHROME:
<img width="1280" alt="chrome snapshot of codepen" src="https://user-images.githubusercontent.com/9588595/27417330-2e2f4122-5731-11e7-8ee0-e8000ca6ef22.png">

(The issue can be seen visually by confirming the width of the items in the blue border.) The Gap beween the blue border and the green border is expected(thats why flex-grow:1 is rejected solution).
Also in actual code where this codepen is used i have added the vendor prefixes for the flex(so thats not a issue)

some related links:-
https://stackoverflow.com/questions/33891709/when-flexbox-items-wrap-in-column-mode-container-does-not-grow-its-width

**Comment by philipwalton** [comment] 2017-06-23 16:47
Thanks for reporting. Can you please update this issue to include all the information outlined in the [reporting guidelines](https://github.com/philipwalton/flexbugs/blob/master/.github/ISSUE_TEMPLATE.md). If the issue is no longer relevant, please close it.

**Comment by vishal9p** [comment] 2017-06-29 06:00
Thanks philip for the info. I have found a trick or some kind of hack is that use flex-flow:column instead of column wrap.Don't know why but it works the way it should.

**Closed** 2017-06-29 18:08 UTC
