### ISSUE TITLE
Flexboxe with margin-bottom in % does not work in Firefox

### ISSUE THREAD

**Issue by slorber** [philipwalton/flexbugs#90] opened 2015-10-30 17:57 UTC
See this JsFiddle: http://jsfiddle.net/mk8uksb2/22/

There should be a vertical space between boxes thanks to margin-bottom: 2%;

On Firefox 41.0.2 (Ubuntu) this margin is ignored (but it works with pixels).

**Comment by philipwalton** [comment] 2015-10-31 01:44
I think this is a duplicate of https://github.com/philipwalton/flexbugs/issues/86, which it actually seems like Firefox is rendering correctly. See [Daniel Holbert's comment](https://github.com/philipwalton/flexbugs/issues/86#issuecomment-151667482) for an explanation of why.

**Closed by philipwalton** 2015-10-31 01:44 UTC

**Comment by dholbert** [comment] 2015-11-06 22:52
I think this is actually different (and less subtle) than #86.  This is https://bugzilla.mozilla.org/show_bug.cgi?id=958714 -- basically, the flexbox spec [requires vertical margins/padding on flex items to be resolved against the container's height](https://drafts.csswg.org/css-flexbox-1/#item-margins). (Note that this is different from what happens in a display:block element, where *all* margin/padding are resolved against the container's width.)

In your jsfiddle, the flex container has no explicit height, so the percentage has nothing to resolve against, so it resolves to 0. If you change your fiddle to give your flex container an explicit height, though, then the 2% will have something to resolve against, and you'll see it render. Example:
https://jsfiddle.net/mk8uksb2/23/

Chrome is non-conforming on this, which is tracked in http://code.google.com/p/chromium/issues/detail?id=333533

I believe Microsoft Edge & Firefox are consistent with each other (and with the spec), though.

**Comment by philipwalton** [comment] 2015-11-07 03:41
Thanks @dholbert!
