### ISSUE TITLE
Min height issue with Chrome and IE11

### ISSUE THREAD

**Issue by skmasq** [philipwalton/flexbugs#144] opened 2016-03-29 11:34 UTC
**[Update]**: #135 this actually solves the problem better, by setting `height: 0` instead of `height: 100%`

So here is a fun bug,

Chrome doesn't know how to calculate height if the min-height **is not** set, and IE doesn't know how to calculate height if the min-height property **is** set.

Code:
```less
.body-content {
    position: relative;
    float: left;
    padding: 0 @SD_General_SidePadding;
    // TODO: This fix is only because of JavaScript perfomring calculations on hight
    padding-bottom: @SD_Footer_height;
    width: 100%;
    overflow: auto;
    min-height: ~"calc(100vh - @{SD_Header_height})";

    .content-columns {
        display: table;
        width: 100%;
        min-height: ~"calc(100vh - @{SD_Header_height} - @{SD_Footer_height})";

        .content-columns-inner {
            #bundle #Flex .dispalyFlexbox();
            #bundle #Flex .flexboxDirection(row);
            // Notes: Different browsers calculate height differently. IE11 can't calculate min-height without table wrapper and other browsers can't caluclate height within table
            // Notes: This one is for IE11+
            height: 100%;
            // Notes: This one is for other browsers
            min-height: ~"calc(100vh - @{SD_Header_height} - @{SD_Footer_height})";
        }
    }
}
```

Solution:

```less
@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
    .body-content{
        .content-columns{
            .content-columns-inner{
                min-height: auto !important; // IE why u no know to calc height with min-height?
            }
        }
    }
}
```

**Comment by jpdevries** [comment] 2016-03-29 13:11
@skmasq any chance you could create a codepin with example markup to demonstrate this bug?
http://codepen.io

**Comment by philipwalton** [comment] 2016-04-26 19:32
I'm going to close this because there's no demo and it's not clear to me what the issue is. Feel free to reopen if you can add a demo and more information.

**Closed by philipwalton** 2016-04-26 19:32 UTC
