### ISSUE TITLE
Flexbug #11 Appears to be Resolved

### ISSUE THREAD

**Issue by somombo** [philipwalton/flexbugs#218] opened 2017-05-07 02:09 UTC
@philipwalton,

Like I mentioned on [twitter](https://twitter.com/mombosolutions/status/824974460608454656), the [official bug filing for Flexbug #11](https://bugs.webkit.org/show_bug.cgi?id=136041) has been closed for a couple months now...

I recently tested using their [example reproduction of the bug](https://bugs.webkit.org/attachment.cgi?id=236805). 

Things appear to be working fine.

Can anybody else confirm that Safari@>10 is correctly wrapping flex items?
I got the following results in Safari 10.1

<img width="800" alt="2column" src="https://cloud.githubusercontent.com/assets/5506400/25777305/1a3de166-329f-11e7-8cfd-7796f96a5dfb.png">
<img width="513" alt="1column" src="https://cloud.githubusercontent.com/assets/5506400/25777306/1e3f1fe6-329f-11e7-86ae-6845907c3c9e.png">

**Comment by somombo** [comment] 2017-06-23 15:59
Ping @philipwalton

**Comment by philipwalton** [comment] 2017-06-23 17:22
Thanks, I can confirm that it's working for me in Safari 10.1.1, and when I test it on 10.0.1 on Sauce Labs I see the broken behavior, so it looks like the fix probably landed in 10.1.

**Comment by philipwalton** [comment] 2017-06-23 17:24
Fixed via 676abf342f9284c0fc616ee9c69006eb35a0b2d6.

**Closed by philipwalton** 2017-06-23 17:24 UTC
