### ISSUE TITLE
Firefox, IE10/11: Flex children that are taken out of the flow with position: absolute can incorrectly affect the flex layout with justify-content

### ISSUE THREAD

**Issue by stowball** [philipwalton/flexbugs#154] opened 2016-05-23 00:56 UTC
When using `justify-content: space-between` (also fails with `space-around`) to align one element to the left and another to the right with a gap in the middle and adding a `position: absolute` element as a flex-child, the `absolute` element incorrectly affects the layout by being thought of as an actual flex-child.

Demo:
http://codepen.io/stowball/pen/eZqgdp

```html
<h1>Button first - affects layout</h1>
<div>
    <button class="floating">top-left absolute</button>
    <p class="left">left</p>
    <p class="right">right</p>
</div>

<h1>Button in middle - doesn't affect layout</h1>
<div>
    <p class="left">left</p>
    <button class="floating">top-left absolute</button>
    <p class="right">right</p>
</div>

<h1>Button last - affects layout</h1>
<div>
    <p class="left">left</p>
    <p class="right">right</p>
    <button class="floating">top-left absolute</button>
</div>
```

```scss
* {
    font-family: sans-serif;
    font-size: 18px;
}

div {
    background: palegoldenrod;
    align-items: center;
    display: flex;
    justify-content: space-between;
    margin-bottom: 10px;
    padding-top: 20px;
    position: relative;
}

.floating {
    position: absolute;
    top: 0;
    left: 0;
}

.left {
    background: pink;
    
    .flex-grow & {
        flex-grow: 1;
    }
}

.right {
    background: orange;
}
```

```js
document.getElementById('toggle').onclick = function () {
    document.body.classList.toggle('flex-grow');
}
```

**Actual results:**
The absolute element is treated as a normal flex child, so when it is the first or last element, it has space incorrectly created for it.

**Expected results:**
Being absolute, it should no longer be thought of as a layout-affecting flex child. It works as expected in Chrome, Safari, Opera and Edge.

If there is no vacant space (such as if you give the first element `flex-grow: 1`) then the absolute button does not affect the layout.

Also logged in Firefox bug tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1274876

**Comment by philipwalton** [comment] 2016-05-28 00:17
Thanks, this is a duplicate of #111, and unfortunately, I don't think there's a workaround.

**Comment by philipwalton** [comment] 2016-05-28 00:18
And for anyone looking, the FF tracking bug for this is here:
https://bugzilla.mozilla.org/show_bug.cgi?id=874718

**Closed by philipwalton** 2016-05-28 00:17 UTC
