### ISSUE TITLE
Bugs 2 and 4 also apply to Chrome

### ISSUE THREAD

**Issue by hrbonz** [philipwalton/flexbugs#30] opened 2015-04-02 14:15 UTC
I had the same issue on:
* Nexus 4, Android 5.0.1, Chrome 41.0.2272.96
* Linux Ubuntu 14.04, Chrome 41.0.2272.101 (64-bit)
* Linux Ubuntu 14.04, Chromium 41.0.2272.76 (64-bit)

Should I create a PR to add them?

**Comment by philipwalton** [comment] 2015-04-08 00:35
I can't reproduce this. Are you looking at the Codepen examples listed in the README? Can you upload a screenshot?

**Comment by hrbonz** [comment] 2015-04-08 03:39
I had it in my code, this exact situation. Didn't try the codepen as I found your repository after searching for the issue and finding the fix. I'll try to reproduce and upload screenshots.

**Comment by gregwhitworth** [comment] 2016-06-20 21:12
I'm going to close this for now, can you please upload them via the comment if you get around to providing the screenshots?

**Closed by gregwhitworth** 2016-06-20 21:12 UTC
