### ISSUE TITLE
Chrome: overriding justify-content does not work

### ISSUE THREAD

**Issue by evanemolo** [philipwalton/flexbugs#21] opened 2015-02-16 17:21 UTC
http://jsbin.com/nocoperimu/2/edit?html,css,js,output
https://code.google.com/p/chromium/issues/detail?id=451387

Does anyone know of a work-around for this?

**Comment by gregwhitworth** [comment] 2015-02-17 10:35
Ack, that is a nasty one to workaround as justify-content is the long hand so you can't try a different flex-declaration in hopes of finding a way around it. Interestingly enough this only affects the space-* values for justify-content. If you declare flex-start or flex-end it work interopably with [FF/IE](http://jsbin.com/qeqifopuba/1/edit?html,css,js,output). The only try way to work around this (that I can think of) is to do the math yourself in JS, but that seems like a lot of work when the issue isn't seen in Chrome Canary (so they seem to have fixed it). Also, depening on the scenario you may be able to work around it uitilizing some fancy padding or margin work. Not desirable but you should only have to hack it in for a quarter or two until Chrome 42 is released.

**Comment by philipwalton** [comment] 2015-02-18 03:08
Yeah, it sounds like this has been fixed in Chrome 41, so it'll be live in a few weeks. I also can't think of any good workarounds, so I guess I'll just close this issue since it'll go away soon.

**Closed by philipwalton** 2015-02-18 03:08 UTC

**Comment by evanemolo** [comment] 2015-02-18 15:37
Great, thanks for the help.
